version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: springboot-backend
    ports:
      - "8089:8089"
    volumes:
      - ./data:/data
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      CLOAUDINARY_CLOUD_NAME: ${CLOAUDINARY_CLOUD_NAME}
      CLOAUDINARY_API_KEY: ${CLOAUDINARY_API_KEY}
      CLOAUDINARY_API_SECRET: ${CLOAUDINARY_API_SECRET}

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "5173:80"
    stdin_open: true
    tty: true

volumes:
  mysql-data:
